services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3010:80"
